[Network]
Type="channel"
CAFile="sdk/ca.crt"
Cert="sdk/sdk.crt"
Key="sdk/sdk.key"

[[Network.Connection]]
NodeURL="192.168.226.133:20200"
GroupID=1

[Account]
KeyFile="account/admin_key_0x2db2e97e20f1571f135bf657e7d6d29ba63c1b8a.pem"


[Chain]
ChainID=1
SMCrypto=false

[log]
Path="./"
